In [1]:
import numpy as np

### Creating Arrays

Create a list and convert into numpy arrays

In [4]:
my_list = [1 , 2 , 3 , 4]
x = np.array(my_list)
x
#print(x)

array([1, 2, 3, 4])

Or just pass in a list directly

In [6]:
y = np.array([1 , 2 , 2])
y
#print(y)

array([1, 2, 2])

Pass in a list of lists to create a multidimensional array.

In [10]:
multi_dimension = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
multi_dimension
#print(multi_dimension)

[[1 2 3]
 [4 5 6]]


Use the shape method to find the dimensions of the array. (rows, columns)

In [13]:
print(multi_dimension.shape)

(2, 3)


arange returns evenly spaced values within a given interval.

In [18]:
arrange = np.arange( 0 , 30 , 2) # start up 0 count up to 2 and end before 30
arrange
#print(arrange)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

reshape returns an array with the same data with a new shape.

In [19]:
reshape = arrange.reshape(3 , 5) # reshape array to be 3 * 5
reshape

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

linspace returns evenly spaced numbers over a specified interval.

In [21]:
line_space = np.linspace(0 , 4 , 9) # return 9 evenly spaced values from 0 to 4
line_space
#print(line_space)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])


resize changes the shape and size of array in-place.

In [24]:
resize = line_space.resize(3 , 3)
line_space

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])


ones returns a new array of given shape and type, filled with ones.

In [25]:
np.ones((3 , 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

zeros returns a new array of given shape and type, filled with zeros.

In [26]:
np.zeros((3 , 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])


eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

diag extracts a diagonal or constructs a diagonal array.

In [29]:
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])


Create an array using repeating list (or see np.tile)

In [30]:
np.array([1 , 2 , 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Repeat elements of an array using repeat.

In [32]:
np.repeat([1 , 2 , 3] , 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## Combining Arrays

In [33]:
x = np.ones([2 , 3] , int)
x

array([[1, 1, 1],
       [1, 1, 1]])

Use vstack to stack arrays in sequence vertically (row wise).

In [36]:
np.vstack([x , 2 * x])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])


Use hstack to stack arrays in sequence horizontally (column wise).

In [37]:
np.hstack([x , 2 * x])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.

In [41]:
x = np.array([1 , 2 , 3])
y = np.array([5 , 6 , 7])

In [43]:
print (x + y)    # elementwise addition        [1 2 3] + [5 6 7] = [6  8  10]
print(x - y)     # elementwise Subtraction     [1 2 3] - [5 6 7] = [-4  -4  -4]

[ 6  8 10]
[-4 -4 -4]


In [44]:
print(x * y )      # elementwise multiplication     [1 2 3] * [4 5 6] = [ 5 12 21]
print(x / y )      # elementwise division           [1 2 3] / [4 5 6] = [0.2 0.33333333 0.42857143]

[ 5 12 21]
[0.2        0.33333333 0.42857143]


In [45]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


### Dot Product 



$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [46]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

38

In [47]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [48]:
z = np.array([y , y**2])
z

array([[ 5,  6,  7],
       [25, 36, 49]])

The shape of array z is (2,3) before transposing.

In [49]:
z.shape

(2, 3)

Use .T to get the transpose.

In [50]:
z.T

array([[ 5, 25],
       [ 6, 36],
       [ 7, 49]])

The number of rows has swapped with the number of columns.

In [51]:
z.T.shape

(3, 2)


Use .dtype to see the data type of the elements in the array.

In [52]:
z.dtype

dtype('int64')

Use .astype to cast to a specific type.

In [54]:
z = z.astype('f')
z.dtype

dtype('float32')

## Math Functions 

Numpy has many built in math functions that can be performed on arrays.

In [55]:
a = np.array([-4 , -3 , -2 , -1 , 0 , 1 , 2 , 3 , 4])
a

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [56]:
a.sum()

0

In [57]:
a.max()

4

In [58]:
a.min()

-4

In [59]:
a.mean()

0.0

In [60]:
a.std()

2.581988897471611

argmax and argmin return the index of the maximum and minimum values in the array.

In [61]:
a.argmax()

8

In [62]:
a.argmin()

0

## Indexing / Slicing

In [64]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])


Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [65]:
s[0] , s[5] , s[-1]

(0, 25, 144)

Use : to indicate a range. array[start:stop]

Leaving start or stop empty will default to the beginning/end of the array.

In [66]:
s[0:5]

array([ 0,  1,  4,  9, 16])


Use negatives to count from the back.

In [67]:
s[4:]

array([ 16,  25,  36,  49,  64,  81, 100, 121, 144])

In [68]:
s[:4]

array([0, 1, 4, 9])

A second : can be used to indicate step-size. array[start:stop:stepsize]

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [69]:
s[-5 :: -2]

array([64, 36, 16,  4,  0])

In [70]:
s[ 2 :: 5]

array([  4,  49, 144])

Let's look at a multidimensional array.

In [71]:
r = np.arange(36)
r.resize((6 , 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: array[row, column]

In [72]:
r[2 , 2]

14

And use : to select a range of rows or columns

In [73]:
r[3 , 3:6]

array([21, 22, 23])

Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [74]:
r[:2 , :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

This is a slice of the last row, and only every other element.

In [76]:
r[-1 , ::2]

array([30, 32, 34])

We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see np.where)

In [77]:
r[r > 30]

array([31, 32, 33, 34, 35])


Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [78]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Copying Data

Be careful with copying and modifying arrays in NumPy!

r2 is a slice of r

In [80]:
r2 = r[:3 , :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Set this slice's values to zero ([:] selects the entire array)

In [81]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

r has also been changed!

In [82]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])


To avoid this, use r.copy to create a copy that will not affect the original array

In [83]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])


Now when r_copy is modified, r will not be changed.

In [85]:
r_copy[:] = 10
print(r_copy , '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [86]:
test = np.random.randint(0 , 10 , (4 , 3))
test

array([[9, 4, 3],
       [3, 3, 5],
       [5, 2, 7],
       [7, 1, 2]])


Iterate by row:

In [87]:
for row in test:
    print(row)

[9 4 3]
[3 3 5]
[5 2 7]
[7 1 2]



Iterate by index:

In [88]:
for i in range(len(test)):
    print(test[i])

[9 4 3]
[3 3 5]
[5 2 7]
[7 1 2]


Iterate by row and index:

In [89]:
for i, row in enumerate(test):
    print('row' , i , 'is' , row) 

row 0 is [9 4 3]
row 1 is [3 3 5]
row 2 is [5 2 7]
row 3 is [7 1 2]


Use zip to iterate over multiple iterables.

In [90]:
test2 = test ** 2
test2

array([[81, 16,  9],
       [ 9,  9, 25],
       [25,  4, 49],
       [49,  1,  4]])

In [91]:
for i , j in zip(test , test2):
    print(i , "+" , j , "=" , i + j)

[9 4 3] + [81 16  9] = [90 20 12]
[3 3 5] + [ 9  9 25] = [12 12 30]
[5 2 7] + [25  4 49] = [30  6 56]
[7 1 2] + [49  1  4] = [56  2  6]
